Simple examples how to use pREST
prest/prest-example pull request #1
Opened 2018-03-03 00:50 UTC by crgimenes

Simple examples of how to use pREST in your Go code

2018-03-03 01:09 UTC, marioidival requested changes
some typos

2018-03-03 01:09 UTC, marioidival commented on custom-middlewares/README.md
> +Then you can access the url http://localhost:3000/ping and in this case the sertver will return `Calling custom middleware` and then `Pong!` as response.
typo, sertver

2018-03-03 01:09 UTC, marioidival commented on extending-framework/README.md
> +To run extending framework example with local database configure the following envaironment variables
typo envaironment

2018-03-03 13:46 UTC, marioidival approved these changes
👑  LGTM 👑

2018-03-03 16:13 UTC, lerrua commented on custom-middlewares/README.md
> +To run extending framework example with local database configure the following envaironment variables
typo envaironment (environment)

2018-03-03 16:14 UTC, lerrua commented on extending-framework/README.md
> +In this example we desabled the JWT with the `PREST_JWT_DEFAULT=false` environment variable.
typo desabled (disabled)

2018-03-04 18:35 UTC, crgimenes commented on custom-middlewares/README.md
> +To run extending framework example with local database configure the following envaironment variables
@lerrua typo corrected :D

2018-03-04 18:35 UTC, crgimenes commented on extending-framework/README.md
> +In this example we desabled the JWT with the `PREST_JWT_DEFAULT=false` environment variable.
@lerrua typo corrected :D

2018-03-05 14:51 UTC, merged